package com.softdesign.devintensive.utils;

/**
 * Created by veren on 23.06.2016.
 */
public interface ConstantManager {

    String TAG_PREFIX = "DEV ";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_MAIL_KEY = "USER_MAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_BIO_KEY = "USER_BIO_KEY";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 200;
    int REQUEST_GALLERY_PICTURE = 201;

    String USER_PHOTO_KEY = "MAIN_USER_PHOTO";
    int PERMISSON_SETTING_REQUEST_CODE = 202;
    int PERMISSION_CAMERA_REQUEST_CODE = 203;
    int PERMISSION_CALL_REQUEST_CODE = 204;

    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
    String USER_ID_KEY = "USER_ID_KEY";

    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";

    String USER_FIRST_NAME_VALUE = "USER_FIRST_NAME_VALUE";
    String USER_SECOND_NAME_VALUE ="USER_SECOND_NAME_VALUE";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";

    String PARCELABLE_KEY = "PARCELABLE_KEY";
}
